language: python
python:
  - "3.6" 

# command to install dependencies
install:
  - pip3 install --upgrade setuptools==41.0.0
  - pip3 install .
#   - pip3 install -r requirements.txt

# commands to run tes
# before_script: redis-cli ping

script:
  - python3.6 ./tests/contrastive/test_CEM_MAF.py
  - python3.6 ./tests/contrastive/test_CEM.py
  - python3.6 ./tests/protodash/test_PDASH.py
  - python3.6 ./tests/ted/test_TED_Cartesian.py
  - CUDA_VISIBLE_DEVICES="" python3.6 ./tests/dipvae/test_DIPVAE.py
  - python3.6 ./tests/rbm/test_Boolean_Rule_CG.py
  - python3.6 ./tests/rbm/test_Linear_Rule_Regression.py
  - python3.6 ./tests/rbm/test_Logistic_Rule_Regression.py
  - python3.6 ./tests/lime/test_lime.py
  - python3.6 ./tests/shap/test_shap.py
  - python3.6 ./tests/sif/test_SIF.py
  - python3.6 ./tests/sif/test_SIF.py
after_success:
#  - codecov

services:
#  - redis-server
